#!/bin/bash
set -euo pipefail
echo "This script sets up the MusicBrainz database and the PostgREST API service so that pod4u can operate. It assumes that WSL is installed on Windows along with a Linux distro. It also assumes that you are running it from the 'musicbrainz' directory within the pod4u structure, and so will not work otherwise."
rm -rf ./.musicbrainz-docker /var/cache/apt/partial && mkdir ./.musicbrainz-docker && USERNAME="$1" && shift && systemctl --user stop docker && export PATH=/usr/bin:/usr/bin/apt:$PATH && sudo apt update && sudo apt upgrade -y && sudo rm -rf ./.postgrest /usr/local/bin/docker-volume-snapshot /usr/local/bin/stack /home/$USERNAME/bin/dockerd
sudo apt install -y git curl dpkg lsb-release uidmap dbus-user-session fuse-overlayfs grep coreutils archivemount bzip2 socat && sudo chown -R "$USERNAME" /var/lib/apt/lists /var/lib/dpkg /var/cache/apt /usr/local/bin ./* && git clone https://github.com/metabrainz/musicbrainz-docker ./.musicbrainz-docker && USER=$(id -u)
sudo rm /var/run/docker.sock && sudo apt purge -y docker-ce docker-ce-cli && sudo rm -rf /var/lib/docker /var/lib/containerd && sudo install -m 0755 -d /etc/apt/keyrings && curl -fsSL https://download.docker.com/linux/debian/gpg | sudo tee /etc/apt/keyrings/docker.asc && export FORCE_ROOTLESS_INSTALL=1 >> ~/.bashrc
sudo apt remove -y docker-ce docker-ce-cli && sudo apt autoremove -y && echo "deb [trusted=yes arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null && sudo apt install -y docker-ce docker-ce-cli containerd.io
curl -sSL https://get.haskellstack.org | sh && mkdir ./.postgrest && cd ./.postgrest && git clone https://github.com/PostgREST/postgrest.git . && stack build --install-ghc --copy-bins --allow-different-user --local-bin-path /usr/local/bin && export PATH=/home/"$USERNAME"/.local/bin:/usr/local/bin:/usr/local/bin/postgrest:./postgrest:$PATH >> ~/.bashrc
cd ../ && curl -SL https://raw.githubusercontent.com/junedkhatri31/docker-volume-snapshot/main/docker-volume-snapshot -o /usr/local/bin/docker-volume-snapshot && chmod +x /usr/local/bin/docker-volume-snapshot && export PATH=/usr/local/bin/docker-volume-snapshot:$PATH >> ~/.bashrc && sudo rm /mnt/pgdata && sudo mkdir /mnt/pgdata
mkdir /var/cache/apt/partial && sudo chown -R $USERNAME /var/cache/apt/partial && source ~/.bashrc && sudo apt install -y iptables libpq-dev libgmp-dev zlib1g-dev && curl -fsSL https://get.docker.com/rootless -o $HOME/bin/rootless.sh | sh && echo 'export PATH="$HOME:$HOME/bin:$HOME/.local/bin:$PATH"' >> ~/.bashrc && source ~/.bashrc && chmod +x $HOME/bin/rootless.sh
$HOME/bin/rootless.sh install --force && echo "export XDG_RUNTIME_DIR=$HOME/.docker/run" >> ~/.bashrc && echo "export DOCKER_HOST=unix:///run/user/$(id -u)/docker.sock" >> ~/.bashrc && source ~/.bashrc && /usr/bin/systemctl --user enable docker --now && /usr/bin/systemctl --user start docker --now #&& cat xaa xab xac xad xae xaf xag xah xai > pgdata.tar.bz2
sudo loginctl enable-linger $(whoami) && sudo apt install -y docker-ce-rootless-extras && ~/bin/docker rm mb && ~/bin/docker import ./musicbrainz.tar musicbrainz:latest && ~/bin/docker buildx build . -t mb:latest && socat TCP-LISTEN:2375, fork UNIX-CONNECT:/var/run/docker.sock && sudo cp ./docker-tcp-proxy.service /etc
docker run -it --name mb -d -h localhost -p 5432:5432 -e POSTGRES_USER=musicbrainz -e POSTGRES_PASSWORD=musicbrainz -e POSTGRES_DB=musicbrainz_db -v pgdata:/var/lib/postgresql mb:latest /bin/bash && sudo systemctl daemon-reload && sudo systemctl enable docker-tcp-proxy && sudo systemctl start docker-tcp-proxy
#rm xaa xab xac xad xae xaf xag xah xai ./pgdata.tar.bz2