#!/bin/bash
set -euo pipefail
echo "This script sets up the MusicBrainz database and the PostgREST API service so that pod4u can operate. It assumes that WSL is installed on Windows along with a Linux distro. It also assumes that you are running it from the 'musicbrainz' directory within the pod4u structure, and so will not work otherwise."
echo "Line 4:" && sudo rm -rf ./.musicbrainz-docker /var/cache/apt/partial $HOME/bin && mkdir ./.musicbrainz-docker && USERNAME="$1" && shift && export PATH=/usr/bin:/usr/bin/apt:$PATH && sudo rm -rf ./.postgrest /usr/local/bin/docker-volume-snapshot /usr/local/bin/stack /home/$USERNAME/bin/dockerd /temp && sudo mkdir /temp && mkdir $HOME/bin && sudo chown $USERNAME: /temp $HOME/bin
echo "Line 5:" && sudo apt install -y git curl dpkg lsb-release uidmap dbus-user-session fuse-overlayfs grep coreutils bzip2 g++ slirp4netns libpq-dev zlib1g zlib1g-dev libgmp-dev iptables && sudo chown -R $USERNAME: /var/lib/apt/lists /var/lib/dpkg /var/cache/apt /usr/local/bin && sudo git clone https://github.com/metabrainz/musicbrainz-docker ./.musicbrainz-docker && USER=$(id -u) && export LC_ALL=en_US.UTF-8 && export LANG=en_US.UTF-8
echo "Line 6:" && sudo rm /var/run/docker.sock && sudo apt purge -y docker-ce docker-ce-cli containerd.io && sudo rm -rf /var/lib/docker /var/lib/containerd && sudo install -m 0755 -d /etc/apt/keyrings && curl -fsSL https://download.docker.com/linux/debian/gpg | sudo tee /etc/apt/keyrings/docker.asc && export FORCE_ROOTLESS_INSTALL=1 >> ~/.bashrc && chmod +w $HOME/bin /temp
echo "Line 7:" && sudo apt remove -y docker-ce docker-ce-cli && sudo apt autoremove -y && echo "deb [trusted=yes arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null #&& sudo apt install -y runc containerd docker-ce docker-ce-cli
echo "Line 8:" && sudo apt install haskell-stack -y && sudo mkdir ./.postgrest && cd ./.postgrest && sudo git clone https://github.com/PostgREST/postgrest.git . && sudo stack build --fast --install-ghc --copy-bins --allow-different-user --local-bin-path /usr/local/bin && export PATH=/home/"$USERNAME"/.local/bin:/usr/local/bin:/usr/local/bin/postgrest:./postgrest:$PATH >> ~/.bashrc
echo "Line 9:" && cd ../ && curl -SL https://raw.githubusercontent.com/junedkhatri31/docker-volume-snapshot/main/docker-volume-snapshot -o /usr/local/bin/docker-volume-snapshot && chmod +x /usr/local/bin/docker-volume-snapshot && export PATH=/usr/local/bin/docker-volume-snapshot:$PATH >> ~/.bashrc
echo "Line 10:" && mkdir /var/cache/apt/partial && chown -R $USERNAME /var/cache/apt/partial && source ~/.bashrc && curl -fsSL https://get.docker.com/rootless -o /temp/rootless.sh | sh && echo 'export PATH="$HOME:$HOME/bin:$HOME/.local/bin:$PATH"' >> ~/.bashrc && source ~/.bashrc
echo "Line 11:" && sudo chown $USERNAME: /temp/rootless.sh && echo "export XDG_RUNTIME_DIR=$HOME/.docker/run" >> ~/.bashrc && echo "export DOCKER_HOST=unix:///run/user/$(id -u)/docker.sock" >> ~/.bashrc && source ~/.bashrc && chmod +x /temp/rootless.sh && /temp/rootless.sh install --force && /usr/bin/systemctl --user enable docker --now && /usr/bin/systemctl --user start docker --now #&& cat xaa xab xac xad xae xaf xag xah xai > pgdata.tar.bz2
echo "Line 12:" && sudo apt update && sudo apt install -y containerd.io docker-ce docker-ce-cli docker-ce-rootless-extras --fix-missing && docker-volume-snapshot ./pgdata.tar.bz2 pgdata && ~/bin/docker rm -f mb 2>/dev/null && ~/bin/docker load -i musicbrainz.tar && ~/bin/docker buildx build . -t mb:latest #&& socat TCP-LISTEN:2375, fork UNIX-CONNECT:/var/run/docker.sock && cp ./docker-tcp-proxy.service /etc
echo "Line 13:" && ~/bin/docker run -it --name mb -d -h localhost -p 5432:5432 -e POSTGRES_USER=musicbrainz -e POSTGRES_PASSWORD=musicbrainz -e POSTGRES_DB=musicbrainz_db -v pgdata:/var/lib/postgresql mb:latest && rm xaa xab xac xad xae xaf xag xah xai ./pgdata.tar.bz2 && chown -R $USERNAME /var/run/docker.sock #&& systemctl daemon-reload && systemctl enable docker-tcp-proxy && systemctl start docker-tcp-proxy
